var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/providers/[id]/test/route.js")
R.c("server/chunks/[root-of-the-server]__0y8-hm3._.js")
R.c("server/chunks/_20rprqd._.js")
R.c("server/chunks/[root-of-the-server]__0kaojkt._.js")
R.c("server/chunks/open-sse_0kndpwy._.js")
R.c("server/chunks/[root-of-the-server]__1bv8fsu._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/node_modules_undici_09u721i._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/src_app_api_providers_[id]_test_testUtils_1i592h0.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_providers_[id]_test_route_actions_1z26dtr.js")
R.m(975526)
module.exports=R.m(975526).exports
