var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/oauth/gitlab/pat/route.js")
R.c("server/chunks/[root-of-the-server]__1-l-wd1._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__1q9jms_._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_oauth_gitlab_pat_route_actions_1qbxab0.js")
R.m(350802)
module.exports=R.m(350802).exports
