var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/check/route.js")
R.c("server/chunks/[root-of-the-server]__1qn-tgb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__1q9jms_._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_1x5enyw._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_check_route_actions_0vfk7dc.js")
R.m(636037)
module.exports=R.m(636037).exports
