var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/media-providers/tts/deepgram/voices/route.js")
R.c("server/chunks/[root-of-the-server]__1rojbzy._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__1oejiv2._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/1oeh_server_app_api_media-providers_tts_deepgram_voices_route_actions_0hjhz53.js")
R.m(670105)
module.exports=R.m(670105).exports
