var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/models/route.js")
R.c("server/chunks/_20rprqd._.js")
R.c("server/chunks/open-sse_providers_1s53fqd._.js")
R.c("server/chunks/[root-of-the-server]__13mu2se._.js")
R.c("server/chunks/[root-of-the-server]__0r262jf._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_models_route_actions_1h6mkqp.js")
R.m(837828)
module.exports=R.m(837828).exports
