var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/route.js")
R.c("server/chunks/open-sse_services_accountFallback_08a593v.js")
R.c("server/chunks/open-sse_1996e_g._.js")
R.c("server/chunks/[root-of-the-server]__1oejiv2._.js")
R.c("server/chunks/open-sse_providers_1s53fqd._.js")
R.c("server/chunks/[root-of-the-server]__1om2gfl._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_settings_route_actions_1bpm9ac.js")
R.m(810638)
module.exports=R.m(810638).exports
