var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/providers/route.js")
R.c("server/chunks/_20rprqd._.js")
R.c("server/chunks/[root-of-the-server]__19-m2s8._.js")
R.c("server/chunks/[root-of-the-server]__0347m7a._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/_next-internal_server_app_api_providers_route_actions_0p8so7l.js")
R.m(502604)
module.exports=R.m(502604).exports
