var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/proxy-pools/vercel-deploy/route.js")
R.c("server/chunks/[root-of-the-server]__1w9hqxo._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__1q9jms_._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_proxy-pools_vercel-deploy_route_actions_1ug2k9v.js")
R.m(868259)
module.exports=R.m(868259).exports
