var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/audio/transcriptions/route.js")
R.c("server/chunks/_0ezkjju._.js")
R.c("server/chunks/[root-of-the-server]__00je7h4._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_20fuwxf.js")
R.c("server/chunks/[root-of-the-server]__0-_tr8t._.js")
R.c("server/chunks/open-sse_services_accountFallback_08a593v.js")
R.c("server/chunks/[root-of-the-server]__0hwwjhj._.js")
R.c("server/chunks/[root-of-the-server]__0v883kh._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_audio_transcriptions_route_actions_1_vb3iz.js")
R.m(618943)
module.exports=R.m(618943).exports
