var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/providers/[id]/models/route.js")
R.c("server/chunks/_0se2q9-._.js")
R.c("server/chunks/[root-of-the-server]__1sj8_8b._.js")
R.c("server/chunks/open-sse_0kndpwy._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_00xlrd-.js")
R.c("server/chunks/[root-of-the-server]__1oejiv2._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/[root-of-the-server]__0vfufl-._.js")
R.c("server/chunks/_next-internal_server_app_api_providers_[id]_models_route_actions_11wk8l2.js")
R.m(861068)
module.exports=R.m(861068).exports
