var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/media-providers/tts/voices/route.js")
R.c("server/chunks/open-sse_handlers_ttsProviders_index_186-vkz.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0-qfx4x._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/_next-internal_server_app_api_media-providers_tts_voices_route_actions_1ko28_s.js")
R.m(622160)
module.exports=R.m(622160).exports
