var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/models/[kind]/route.js")
R.c("server/chunks/_0m7mnn0._.js")
R.c("server/chunks/open-sse_services_accountFallback_08a593v.js")
R.c("server/chunks/[root-of-the-server]__1ngrquj._.js")
R.c("server/chunks/[root-of-the-server]__0v883kh._.js")
R.c("server/chunks/[root-of-the-server]__1ymiee9._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/open-sse_providers_1s53fqd._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/[root-of-the-server]__0-_tr8t._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/_1grnl4v._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_models_[kind]_route_actions_1jwh_4s.js")
R.m(919204)
module.exports=R.m(919204).exports
