var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cli-tools/cowork-settings/route.js")
R.c("server/chunks/[root-of-the-server]__1nux6-u._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0z0-zra._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_cli-tools_cowork-settings_route_actions_0gwrnn7.js")
R.m(784561)
module.exports=R.m(784561).exports
