var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/usage/chart/route.js")
R.c("server/chunks/[root-of-the-server]__00u0zmd._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__0o1qcc4._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_usage_chart_route_actions_13iv7k_.js")
R.m(31984)
module.exports=R.m(31984).exports
