var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/providers/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__1o17d0b._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__1q9jms_._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_providers_[id]_route_actions_0zf5m7j.js")
R.m(128676)
module.exports=R.m(128676).exports
