var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/version/update/route.js")
R.c("server/chunks/_20rprqd._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__16jqm5i._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/open-sse_providers_1k455ee._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/_next-internal_server_app_api_version_update_route_actions_1rvkc84.js")
R.m(541639)
module.exports=R.m(541639).exports
