var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/combos/route.js")
R.c("server/chunks/[root-of-the-server]__1999p3p._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__1oejiv2._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/_next-internal_server_app_api_combos_route_actions_17e5ruv.js")
R.m(673929)
module.exports=R.m(673929).exports
