var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/oidc/test/route.js")
R.c("server/chunks/[root-of-the-server]__12dx88w._.js")
R.c("server/chunks/_10wez6w._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/[root-of-the-server]__1xppcj4._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_0h8jg99._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_oidc_test_route_actions_00jggnb.js")
R.m(158671)
module.exports=R.m(158671).exports
