var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/oauth/codebuddy/quota-cookie/route.js")
R.c("server/chunks/[root-of-the-server]__1wmgamy._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/[root-of-the-server]__1q9jms_._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_oauth_codebuddy_quota-cookie_route_actions_11sl8zo.js")
R.m(36890)
module.exports=R.m(36890).exports
