var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hagv2c._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0u68oqs.js")
R.c("server/chunks/ssr/[root-of-the-server]__1-_3wj3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/src_app_global-error_0imf2kw.js")
R.c("server/chunks/ssr/_next-internal_server_app__global-error_page_actions_0zi5s8-.js")
R.m(925730)
module.exports=R.m(925730).exports
