var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/tunnel/tailscale-check/route.js")
R.c("server/chunks/[root-of-the-server]__13mu2se._.js")
R.c("server/chunks/[root-of-the-server]__0cbphlr._.js")
R.c("server/chunks/src_lib_tunnel_index_0pu743p.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1btm11j._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/src_lib_db_18rbtbt._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/_next-internal_server_app_api_tunnel_tailscale-check_route_actions_1-fu8wd.js")
R.m(896747)
module.exports=R.m(896747).exports
